#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M -XX:+UseParallelGC
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.js.yarn.ignore.scripts=true

#Gradle
org.gradle.jvmargs=-Xmx6144M -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#关闭configuration-cache解决CI失败的问题，关联bug：https://youtrack.jetbrains.com/projects/KT/issues/KT-77732/commonizeCInterop-failed-with-Unresolved-classifier-platform-posix-sizet
org.gradle.configuration-cache=false
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

# ERROR: Compose targets '[macos]' are experimental and may have bugs!
org.jetbrains.compose.experimental.macos.enabled=true

lalilu.disable.ios.targets=false