#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8192M -XX:+UseParallelGC
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.js.yarn.ignore.scripts=true

#Gradle
org.gradle.jvmargs=-Xmx12288M -XX:MaxMetaspaceSize=1024M -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false

org.gradle.caching=true
org.gradle.vfs.watch=true

#KSP
ksp.incremental=true
ksp.incremental.log=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

# ERROR: Compose targets '[macos]' are experimental and may have bugs!
org.jetbrains.compose.experimental.macos.enabled=true

# Windows环境无法编译iOS相关代码，需要disable掉iOS源集，注意要在local.properties里配置（默认为false）
# lalilu.disable.ios.targets=true