[versions]
agp = "8.11.1"
android-targetSdk = "36"
android-minSdk = "23"
androidx-activity = "1.12.2"
androidx-core = "1.17.0"
androidx-test = "1.7.0"
androidx-lifecycle = "2.9.5"
composeMultiplatform = "1.11.0-alpha01"
kotlinx-serialization = "1.9.0"
junit = "4.13.2"
kotlin = "2.3.10"
kotlin-test = "2.3.20-RC3"
ksp = "2.3.6"
kotlinx-coroutines = "1.10.2"
krouter = "0.0.4"
filekit = "0.12.0"
koin = "4.1.1"
koin-ksp = "2.3.0"
coil = "3.3.0"
settings = "1.3.0"
kermit = "2.0.8"
krpc = "0.9.1"
ktor = "3.3.0"
ktorfit = "2.7.2"
kotlinx-io = "0.8.0"
kotlinx-datetime = "0.7.1"
kotlinx-browser = "0.5.0"
vlcj = "4.11.0"
media3 = "1.8.0"
room3 = "3.0.0-alpha01"
sqlite = "2.7.0-alpha01"
paging = "3.5.0-alpha01"
rococoa = "4d401915af"
human-readable = "1.12.0"
xmlutil = "0.91.2"
materialKolor = "4.0.4"
flowmvi = "3.2.1"
sweetspi = "0.1.3"
vanniktech-publish = "0.35.0"
jna = "5.18.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-test" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-test" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-test-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }

# kotlinx
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }

# jb-compose
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composeMultiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material:material3", version.ref = "composeMultiplatform" }
compose-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version = "1.2.0-beta01" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }

# jb-androidx
#jbx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version = "1.1.0-alpha01" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version = "1.1.0-alpha01" }
jbx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
jbx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
jbx-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version = "2.10.0-alpha03" }
jbx-navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version = "1.0.0-rc02" }

krouter-core = { module = "io.github.cy745.KRouter:core", version.ref = "krouter" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version = "7.0.3" }
human-readable = { module = "nl.jacobras:Human-Readable", version.ref = "human-readable" }
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }
qrcode-kotlin = { module = "io.github.g0dkar:qrcode-kotlin", version = "4.5.0" }
sonner = { module = "io.github.brdominguez:compose-sonner", version = "0.4.0" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }

# koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }
native-lib-loader = { module = "org.scijava:native-lib-loader", version = "2.5.0" }

# coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }

settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-make-observable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "settings" }
settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settings" }
settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "settings" }
settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }

remixicon-kmp = { module = "io.github.cy745:remixicon-kmp", version = "0.0.2" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
rococoa-core = { module = "com.github.cy745.rococoa:core", version.ref = "rococoa" }
rococoa-contrib = { module = "com.github.cy745.rococoa:contrib", version.ref = "rococoa" }
rococoa-cocoa = { module = "com.github.cy745.rococoa:cocoa", version.ref = "rococoa" }
jna-platform = { module = "net.java.dev.jna:jna-platform-jpms", version.ref = "jna" }
jna = { module = "net.java.dev.jna:jna-jpms", version.ref = "jna" }

# media3
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }

room3-common = { module = "androidx.room3:room3-common", version.ref = "room3" }
room3-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room3" }
room3-paging = { module = "androidx.room3:room3-paging", version.ref = "room3" }
room3-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room3" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
sqlite-web = { module = "androidx.sqlite:sqlite-web", version.ref = "sqlite" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

flowmvi-core = { module = "pro.respawn.flowmvi:core", version.ref = "flowmvi" }
flowmvi-test = { module = "pro.respawn.flowmvi:test", version.ref = "flowmvi" }
flowmvi-compose = { module = "pro.respawn.flowmvi:compose", version.ref = "flowmvi" }
flowmvi-android = { module = "pro.respawn.flowmvi:android", version.ref = "flowmvi" }
flowmvi-savedstate = { module = "pro.respawn.flowmvi:savedstate", version.ref = "flowmvi" }
flowmvi-debugger = { module = "pro.respawn.flowmvi:debugger-plugin", version.ref = "flowmvi" }

sweetspi-runtime = { module = "dev.whyoleg.sweetspi:sweetspi-runtime", version.ref = "sweetspi" }
sweetspi-processor = { module = "dev.whyoleg.sweetspi:sweetspi-processor", version.ref = "sweetspi" }

gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-vanniktech-publish = { module = "com.vanniktech.maven.publish.base:com.vanniktech.maven.publish.base.gradle.plugin", version.ref = "vanniktech-publish" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
krouter-plugin = { id = "io.github.cy745.KRouter.plugin", version.ref = "krouter" }
vanniktech-pulish = { id = "com.vanniktech.maven.publish.base", version.ref = "vanniktech-publish" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
osdetector = { id = "com.google.osdetector", version = "1.7.3" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version = "0.6.0" }
shadowJar = { id = "com.gradleup.shadow", version = "9.3.0" }
room3 = { id = "androidx.room3", version.ref = "room3" }

[bundles]
coil = ["coil-compose", "coil-ktor", "coil-svg"]
settings = ["settings", "settings-coroutines", "settings-make-observable", "settings-no-arg", "settings-serialization"]
rococoa = ["rococoa-cocoa", "rococoa-contrib", "rococoa-core"]
flowmvi = ["flowmvi-core", "flowmvi-test", "flowmvi-compose", "flowmvi-android", "flowmvi-savedstate"]
jbx = [
    "jbx-lifecycle-viewmodel-compose",
    "jbx-lifecycle-runtime-compose",
    "jbx-lifecycle-viewmodel-navigation3",
    "jbx-navigationevent-compose",
]