name: KMP app assemble

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    name: build-android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create the Keystore from Secrets to Sign the App
        env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES_BASE64 }}
        run: |
          # Import keystore from secrets
          ls -all
          echo $KEYSTORE_JKS_BASE64 | base64 -di > ${{ github.workspace }}/keystore.jks
          echo $KEYSTORE_PROPERTIES_BASE64 | base64 -di > ${{ github.workspace }}/keystore.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew composeApp:assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ github.workspace }}/composeApp/build/outputs/apk/release/*.apk

  build-windows:
    name: build-windows
    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew composeApp:packageReleaseMsi
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: ${{ github.workspace }}\composeApp\build\compose\binaries\main-release\msi\*.msi

      
